language: r
before_install:
        - sudo apt-get update
        - sudo apt-get install libssl-dev
        - sudo apt-get install libcurl4-openssl-dev
install: ./travis/inst.R
script: ./tests/run_all_test.R

