#!/usr/bin/Rscript 
# vim:set ff=unix expandtab ts=2 sw=2:

#source("R6_prolog.R")
require(R6Unit)
require(devtools,quiet=TRUE)
#devtools::install('../..')
require(linkeddocs)
#s<-get_suitefromDiscoveredTestInstances(".","^r6unit.*.R")
source("PackageTests.R")
source("PackageTests_3.R")
source("PrototypeTests.R")
#tr<-TestResults$new()
#tc<-PackageTests$new("test.NameSpaceParsing")
tc<-PackageTests$new("test.SoilR")
#tc<-PackageTests$new("test.abbriviatedSignature")
#tc<-PackageTests$new("test.GenericWithDotDotDotArgumets")
#tc<-PackageTests$new("test.OverloadedIndexOperator")
#tc <- PrototypeTests$new("test.package.skeleton.dx_3")
#tc<-PrototypeTests$new("test.correctNameSpaceInfo")
t1 <- PackageTests$new('test.ClassWithMethods')
t2 <- PackageTests_3$new('test.ClassWithMethods')
s<-TestSuite$new(list(t1,t2))
print(s$test_names())
#s$add_test(tc)
tr <- s$run()
#stop(mmsg())

tr$summary()
