#!/usr/bin/Rscript 
# vim:set ff=unix expandtab ts=2 sw=2:

#source("R6_prolog.R")
require(R6Unit)
require(devtools,quiet=TRUE)
#devtools::install('../..')
require(linkeddocs)
#s<-get_suitefromDiscoveredTestInstances(".","^r6unit.*.R")
source("PackageTests_3.R")
source("PrototypeTests.R")
source("ExampleExtractionTest.R")
source("ClassDocTest.R")
#tr<-TestResults$new()
#tc<-PackageTests$new("test.NameSpaceParsing")
#t2<-PackageTests_3$new("test.SoilR")
#t2<-PackageTests_3$new("test.VirtualClass")
#t2<-PackageTests_3$new("test.AutoConstructor")
#t2<-ClassDocTest$new("test.Rd_constructor_lines_for_virtual_class")
#t2<-ClassDocTest$new("test.AutoConstructor_lines")
#t2<-ClassDocTest$new("test.ClassDocXXX")
#t2<-ClassDocTest$new("test.Rd_method_lines")
#t2<-ClassDocTest$new("test.superclass_lines")
#t2<-ClassDocTest$new("test.FindAutoConstructor")
#t2<-ClassDocTest$new("test.subclass_lines")
#t2<-ClassDocTest$new("test.write_Rd_file")
t2<-PackageTests_3$new("test.ClassWithExamples")
#t2<-ExampleExtractionTest$new("test.example_references")
t2<-ExampleExtractionTest$new("test.external_example_lines_for_setClass")
#t2<-ExampleExtractionTest$new("test.external_example_lines_for_function")
#t2<-ExampleExtractionTest$new("test.extract_function_body_with_comments")
#tc<-PackageTests$new("test.abbriviatedSignature")
#tc<-PackageTests$new("test.GenericWithDotDotDotArgumets")
#tc <- PrototypeTests$new("test.package.skeleton.dx_3")
#tc<-PrototypeTests$new("test.correctNameSpaceInfo")
#t2 <- PackageTests_3$new('test.ClassWithMethods')
#t2 <- PackageTests_3$new('test.AutoConstructor')
# t2 <- PackageTests_3$new('test.PrivateAndPublic')
#t1<-PackageTests$new("test.OverloadedIndexOperator")
s<-TestSuite$new(list(t2))
#s<-TestSuite$new(list(t1,t2)) 
print(s$test_names())
s$parallel <- 1 
tr <- s$run()
tr$summary()

